# Generated by Django 5.2.3 on 2025-08-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField()),
                ('last_name', models.CharField()),
                ('date_of_birth', models.DateTimeField()),
                ('gender', models.CharField()),
                ('address', models.CharField()),
                ('phone', models.CharField()),
                ('email', models.CharField()),
                ('emergency_contact', models.CharField()),
            ],
        ),
    ]
